# Generated by Django 4.1.3 on 2022-11-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardchecklistitem',
            name='checklist',
        ),
        migrations.AddField(
            model_name='cardchecklistitem',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='boards.card'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CardCheckList',
        ),
    ]
