# Generated by Django 4.1.3 on 2022-12-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmember',
            old_name='member',
            new_name='user',
        ),
    ]
