# Generated by Django 4.1.3 on 2022-12-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_rename_member_boardmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
