# Generated by Django 4.1.3 on 2022-11-23 10:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_created_on_board_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlabel',
            name='color',
            field=colorfield.fields.ColorField(default='#000', image_field=None, max_length=18, samples=None),
        ),
    ]
