# Generated by Django 4.1.3 on 2022-12-04 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_rename_member_boardmember_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='bar',
            new_name='column',
        ),
        migrations.AlterField(
            model_name='board',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='checklist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='boards.board'),
        ),
    ]
