# Generated by Django 4.1.3 on 2022-11-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_cardchecklistitem_checklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
