# Generated by Django 4.1.3 on 2022-11-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_cardlabel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlabel',
            name='color',
            field=models.CharField(blank=True, default='#3131e8', max_length=50),
        ),
    ]
